language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: l6h7FoHaUX7PjtphTbPMCygmQZG32vARd2I9QWNHX/pE++QhvV1sT7EXrp9pv3f+EDFHe/lETHlAiIaYkjYDC7RXc7wK1HahiYQcDCpYsavi+7lejQW9l6A/y7E0NmYNvpMRY1wZIuypcKTSb5tr9P8M+gTEyCqLCvNCke9ppa90nJm07Vwa+n8WTzDmuZDK9Zzfv1TorW1EfzTtdxlqvbZHZkgj8vn+2ne+oZAvfiALF7IHaWVA2g73omE6nZYwsN9Sf7J4S5+SmgpMSigPUdHBqYMMt21SEGu6LcYjxIRyr/sl/hvw9Lz+zNTdiKRtKMiq6/REMU8uwmE5ntBAKQfivRNAF22C8AR2SCPmSd8M6catDVtYAbuVnAO9B2GepBIZ9WW/lusAD47nRL+JQ9nm3Fs0397nilmxq0hrJHfWgvxqR/1l3R/5/dRzrLNcrdzQWME/VwQriJXY9tHo0XvAA9l0iwP4zKrXx+yIGmjgg2KWTJhtvwK20L1zgCs6Oee22uuvs0zml0t4Vn+YZD51D5QzZNUf+H5f7AeOkv0rOdoQ1fb9bAw0myeB8uzhYQJAvuExjinA/VHRBsTfAsco3z/5cw1pfGBhFFwa4reCXefPtihubrQeallCw6bWhRrz1uKC3po25TXtC5ILXrhYdCfANhe4wPKheToiNn8=
  file:
    - 'web-namespaces.js'
    - 'web-namespaces.min.js'
  on:
    tags: true
