language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  provider: releases
  api_key:
    secure: WE+TCl8qXi6gRSCM93AiMicSA1Vvvkcsm06AltVL0aR5B75Tj/Ar/544EzkNzzePtCwiJyCaiMzAMQts70CN+nAW1T6Wcp9T7zEwJ4cyi3B8NPLuAvBngNVnFGi1pqCviiduDs1z1g0p/whWvYAGgZis4sOi7zeoX4xyu1K58tDePMDK4rF5x2cloa9DQpUTAZ4Og3s3xRDXBsz8d4X4W2dJfL9zrXUgAvTt1FSFR9FeuJp1dx69w8KksisaLL9KdPlj0g9Oxj1LEZc8ySaosqQ11SJ2dLBykYQlzGc+WhYdUUphzIcZ7ExcAu5FUo0DuFpjVJMl8vq8P0+/BUT+A+rB4sZxoWd/ig0OZ/j9t3+XZtVNFaMU0sxwp4MG+N1YyZIQbcXIsrxj7Z5Mx7JehOe7nYFjTktDL/WPtCuLuuXrKrQpChEXRqUqa8vn1ffcZ8B6G0sgNNKNpqiDbzR/hYre675M97cJJkGmX1CuuLXR0N5cLNB1M+ENCz2GR+iLmDG8M5gn/cYs0p8UpQyZ2Bli5oyg4VgUD6BaVIH76UQhB7KmTHqQh8urBr2tweuj+Cwy/FTbR+dRSEq54YCuHgDT4bv4a8NWkXw2FVS/S3uyqoVeVLs2T0r7HfMIidFFqOVQR4Dg/VDHHsthHNE3A4mtUzDw8ZUAEa/n+ecwenQ=
  file:
    - "web-namespaces.js"
    - "web-namespaces.min.js"
  on:
    tags: true
    node: '8.0'
